# Generated by Django 2.2.5 on 2020-10-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20201008_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.Conversation'),
        ),
    ]
